#/********************************************************************************
#*       Author       : Ramguru N
#*       Parameters   : server name, License Key, Ubuntu os codename
#*       Purpose      : Install Newrelic Agent in target machine
#*       Version      : V-1.0
#*       Command      : ansible-playbook newrelic_agent_install.yml -e server_name=<target_machine>
#*********************************************************************************

---
- hosts: 
  become: yes
  gather_facts: false

  vars:
    os_codename: xenial
    license_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  tasks:

    - name: NewRelic | Add apt sources list
      apt_repository:
        repo: deb [arch=amd64] http://download.newrelic.com/infrastructure_agent/linux/apt {{ os_codename }} main
        state: present
      tags: newrelic

    - name: NewRelic | Add GPG key to the apt sources keyring
      apt_key:
        url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
        state: present
      tags: newrelic


    - name: NewRelic | Add license key in the config file
      shell: echo "license_key{{':'}} {{ license_key }}" | sudo tee -a /etc/newrelic-infra.yml
      notify: NewRelic | Restart service
      tags: [newrelic, newrelic-license]

    - name: NewRelic | Add Server Name in the config file
      shell: echo "display_name{{':'}} {{ server_name }}" | sudo tee -a /etc/newrelic-infra.yml
      notify: NewRelic | Restart service
      tags: [newrelic, newrelic-license]

    - name: NewRelic | Run the install command
      apt: pkg=newrelic-infra update_cache=yes
      tags: newrelic

    - name: NewRelic | Check that NewRelic service is started
      systemd:
        name: newrelic-infra
        state: started
        enabled: True
      tags: newrelic

  handlers:

    - name: NewRelic | Restart service
      systemd:
        name: newrelic-infra
        state: restarted
